travis:
  secure:
    BINSTAR_TOKEN: hrPIK4g9bycSkOeEdU3Lb4pXD+mfacSrQWasDvJlMZp0Z2rZAqoHIW4fCHoS5YNwid68Vs4/vxduRD9IlGSmIZMgfvcujFialXSSI1wYgImghkUf0LRtynsmCY4ljFoU3EECtPAIPS4MA62ZPdtMFkH69nUDFHub/10gTOf63VsrRY9iH9grFAmHDwQ5G7X4sssTg+78wrGEhD8jGBdoy/0aAhVo7HK8Q+L+P787R+LXG15tut7RfPg6UWNaPXAb55lZZc2IRN3gvzjBAjEDwrcdWhx23xKMgXmL3cwZ7KirJwUZiWyKCmQ28ydtI2fA2SRCkDKZzzWj4OBQ01mw+HGok0Ya7OdB1tU85FbdCdmEXuuB2CKp5s9lZbL/YIdNfM+mXgLxzOI2fLfT2jDu0oq4gPRpWVTZFV2zE3QRl7vSsUx7ZEsin7Pvyh8up182VTATXhuHXPxwjNO6VShemlJ/o2GrjLX08HTF1VQ6rmdhGDj13AEdHR3XF4XDPLF0IevONMSOp6ZrF0RhJj1LdDfPWN5OTldgRvlD5OP19VyXDUvY9w+p8mxY6vdTmldTyLvjTO63S01IZmZdd5mb7QSHv4p/QXawkpORtQIUQ9MxT+nC7yxG3WpH9TsNREWMuVFRuHyFflG/cAA+bdf51DgXnIWdW0AoZb/pWtlasgo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
